name: waitwhat
description: "A new Flutter project."
publish_to: 'none'
version: 1.2.0+3

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  notification_listener_service: any
  home_widget: any
  drift: ^2.22.0
  drift_flutter: ^0.3.0
  path_provider: ^2.1.0
  shared_preferences: ^2.2.0
  device_info_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.22.0
  build_runner: ^2.4.0
flutter:
  uses-material-design: true
  assets:
    - assets/icon.svg
    - assets/icon_foreground.svg
